### ISSUE TITLE
フレームワークの選定

### ISSUE THREAD

**Issue by AsagaKosho** [tsukuba-shinkan/shinkan-web-orgadmin#1]
このリポジトリ（団体情報管理システム）で使用するフレームワークの選定をします。
いくつか候補を理由とともに挙げていただければ幸いです。

https://github.com/tsukuba-shinkan/shinkan-web/issues/153 にある通り、Reactベースのものを使用することは決定していますので、Reactベースのものでお願いします。

**Comment by nandenjin** [comment]
シンプルにやるならただ単にReactをWebpackでビルドするような構成でいいと思うのですが、SSRや最適化の機能をつける必要性がいずれ生じると思うので、そういう機能が備わったものを推したいです。
知ってる範囲だと[Next.js](https://nextjs.org/)とか……？ 🤔  （プロダクションレベルでは触ったことないので先頭に立って推すのはアレかもですが）

**Comment by AsagaKosho** [comment]
@mkobayashime さんや @yuki-js さんもご意見あればお願いします～！

**Comment by AsagaKosho** [comment]
> シンプルにやるならただ単にReactをWebpackでビルドするような構成でいいと思うのですが、SSRや最適化の機能をつける必要性がいずれ生じると思うので、そういう機能が備わったものを推したいです

この要件満たしてある程度情報もあるものだとNext.jsに限られますかね…？うーん。

**Comment by mkobayashime** [comment]
@asagatto777 僕自身はReact系のフレームワークでちゃんとアプリケーションを書いたことがないので、選定に関して特に意見できることはないです…

**Comment by yuki-js** [comment]
Next.jsがいいと思います。
私はNext.jsを使ったことがないですが。

**Comment by AsagaKosho** [comment]
@nandenjin @mkobayashime @yuki-js 
Next.jsでいきましょう！！
